import React, { createContext, useCallback, useContext, useEffect, useState } from 'react'
import { Link, NavLink, Route, Routes, useLocation, useNavigate, useParams } from 'react-router-dom'
import { Activity, AlertTriangle, ArrowUpRight, BadgeCheck, ChevronDown, ChevronRight, CircleHelp, Clock3, Cpu, Download, Fingerprint, KeyRound, LayoutDashboard, LogOut, Menu, Radio, Search, Settings2, ShieldCheck, SlidersHorizontal, Thermometer, Users, Wind, X } from 'lucide-react'
import { Area, AreaChart, CartesianGrid, Cell, Legend, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { createManagedUser, getAlerts, getAnalytics, getBlocks, getFog, getLatest, getManagedUsers, getMe, getOverview, getReadings, getSimulation, getUser, login as requestLogin, resolveAlert, startSimulation, stopSimulation, verifyBlockchain } from './api'

const RoleContext = createContext('user')

const links = [
  { to: '/', label: 'Overview', icon: LayoutDashboard },
  { to: '/live', label: 'Live monitoring', icon: Radio },
  { to: '/people', label: 'Users & devices', icon: Users },
  { to: '/alerts', label: 'Alerts', icon: AlertTriangle },
  { to: '/history', label: 'Historical data', icon: Clock3 },
  { to: '/analytics', label: 'Risk analysis', icon: Activity },
  { to: '/blockchain', label: 'Blockchain', icon: Fingerprint },
]
const riskName = { LOW: 'Low', MODERATE: 'Moderate', HIGH: 'High' }
const formatTime = value => value ? new Date(value).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' }) : '—'
const formatDate = value => value ? new Date(value).toLocaleString([], { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' }) : '—'

function App() {
  const [open, setOpen] = useState(false)
  const [currentUser, setCurrentUser] = useState(null)
  const [checkingAuth, setCheckingAuth] = useState(Boolean(localStorage.getItem('thermosense-token')))
  const [overview, setOverview] = useState(null)
  const [fog, setFog] = useState(null)
  const [simulation, setSimulation] = useState(null)
  const [alerts, setAlerts] = useState([])
  const [error, setError] = useState('')
  const location = useLocation()
  const navigate = useNavigate()
  const title = links.find(item => item.to === location.pathname)?.label || (location.pathname.startsWith('/people/') ? 'User details' : 'ThermoSense')

  const refresh = useCallback(async () => {
    try {
      const [stats, fogStats, sim, activeAlerts] = await Promise.all([getOverview(), getFog(), getSimulation(), getAlerts({ status: 'ACTIVE', limit: 8 })])
      setOverview(stats); setFog(fogStats); setSimulation(sim); setAlerts(activeAlerts); setError('')
    } catch (e) { setError(e.response?.data?.detail || 'Backend unavailable. Start FastAPI and PostgreSQL to connect live data.') }
  }, [])

  useEffect(() => {
    let live = true
    const token = localStorage.getItem('thermosense-token')
    const expired = () => { if (live) { setCurrentUser(null); setCheckingAuth(false) } }
    window.addEventListener('thermosense-auth-expired', expired)
    if (token) getMe().then(user => { if (live) setCurrentUser(user) }).catch(() => { if (live) { localStorage.removeItem('thermosense-token'); setCurrentUser(null) } }).finally(() => { if (live) setCheckingAuth(false) })
    else setCheckingAuth(false)
    return () => { live = false; window.removeEventListener('thermosense-auth-expired', expired) }
  }, [])
  useEffect(() => { if (!currentUser) return; refresh(); const timer = setInterval(refresh, 3000); return () => clearInterval(timer) }, [refresh, currentUser])
  const toggleSimulation = async config => {
    try { const result = config ? await startSimulation(config) : await stopSimulation(); setSimulation(result); refresh() }
    catch (e) { setError(e.response?.data?.detail || 'Could not update the simulator.') }
  }

  const logout = () => { localStorage.removeItem('thermosense-token'); setCurrentUser(null); setOverview(null); navigate('/login') }
  if (checkingAuth) return <div className="auth-loading"><div className="brand-mark"><Activity size={21}/></div><span>Checking your session…</span></div>
  if (!currentUser) return <LoginScreen onAuthenticated={setCurrentUser}/>

  return <div className="app-shell">
    <aside className={`sidebar ${open ? 'sidebar-open' : ''}`}>
      <div className="brand"><div className="brand-mark"><Activity size={21}/></div><div><strong>Thermo<span>Sense</span></strong><small>FIELD MONITORING</small></div><button className="icon-button mobile-close" onClick={() => setOpen(false)}><X size={19}/></button></div>
      <div className="workspace-label">WORKSPACE</div>
      <nav>{links.map(({ to, label, icon: Icon }) => <NavLink end={to === '/'} key={to} to={to} className={({ isActive }) => `nav-link ${isActive ? 'active' : ''}`} onClick={() => setOpen(false)}><Icon size={18}/><span>{label}</span>{label === 'Alerts' && overview?.active_alerts > 0 && <b className="nav-count">{overview.active_alerts}</b>}</NavLink>)}</nav>
      <div className="sidebar-spacer"/>
      <div className="fog-mini"><div className="fog-mini-head"><span className={`pulse-dot ${fog?.online?'':'offline-dot'}`}/> Fog node <span className={`online-text ${fog?.online?'':'offline-text'}`}>{fog?.online?'Online':'Unavailable'}</span></div><div className="fog-mini-meta"><span>Processed</span><strong>{fog?.processed_readings ?? '—'}</strong></div><div className="fog-mini-meta"><span>Last update</span><strong>{formatTime(fog?.latest_processed_at)}</strong></div></div>
      <div className="sidebar-foot"><div className="avatar">{currentUser.name.slice(0,2).toUpperCase()}</div><div className="profile"><strong>{currentUser.name}</strong><span>{currentUser.role.replace('_',' ')}</span></div><button className="icon-button logout-button" title="Log out" onClick={logout}><LogOut size={16}/></button></div>
    </aside>
    {open && <button className="scrim" onClick={() => setOpen(false)} aria-label="Close menu"/>}
    <main className="main-area">
      <header className="topbar"><button className="icon-button mobile-menu" onClick={() => setOpen(true)}><Menu size={20}/></button><div className="crumb">Monitoring <ChevronRight size={14}/> <strong>{title}</strong></div><div className="top-actions"><span className={`live-indicator ${overview?'':'top-status-offline'}`}><span className="pulse-dot"/> {overview?'Live system':'Connecting'}</span><span className="top-divider"/><span className="updated">Updated {formatTime(overview?.latest_readings?.[0]?.processed_at)}</span><button className="help-button" title="About this prototype"><CircleHelp size={18}/></button></div></header>
      <div className="page-wrap">
        {error && <div className="error-banner"><AlertTriangle size={17}/><span>{error}</span><button onClick={() => { setError(''); refresh() }}>Retry</button></div>}
        <RoleContext.Provider value={currentUser.role}><Routes>
          <Route path="/" element={<Overview overview={overview} fog={fog} simulation={simulation} alerts={alerts} onToggle={toggleSimulation} isAdmin={currentUser.role === 'admin'}/>}/>
          <Route path="/live" element={<LivePage/>}/>
          <Route path="/people" element={<><AccountManager/><PeoplePage/></>}/>
          <Route path="/people/:userId" element={<UserPage/>}/>
          <Route path="/alerts" element={<AlertsPage/>}/>
          <Route path="/history" element={<HistoryPageEnhanced/>}/>
          <Route path="/analytics" element={<RiskAnalysisPage/>}/>
          <Route path="/blockchain" element={<BlockchainPage/>}/>
          <Route path="*" element={<Overview overview={overview} fog={fog} simulation={simulation} alerts={alerts} onToggle={toggleSimulation} isAdmin={currentUser.role === 'admin'}/>}/>
        </Routes></RoleContext.Provider>
        <footer className="disclaimer"><ShieldCheck size={14}/> ThermoSense is an engineering research prototype. Predictions are for demonstration only and are not a clinical diagnosis.</footer>
      </div>
    </main>
  </div>
}

function PageHeading({ eyebrow, title, subtitle, action }) { return <div className="page-heading"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{subtitle}</p></div>{action}</div> }
function StatCard({ icon: Icon, label, value, note, tone = 'blue' }) { return <div className="stat-card"><div className={`stat-icon ${tone}`}><Icon size={19}/></div><div className="stat-copy"><span>{label}</span><strong>{value ?? '—'}</strong><small>{note}</small></div><div className="stat-trend"><ArrowUpRight size={16}/></div></div> }
function RiskPill({ risk }) { return <span className={`risk-pill ${(risk || 'LOW').toLowerCase()}`}><i/>{riskName[risk] || risk || 'Unknown'} risk</span> }

function LoginScreen({ onAuthenticated }) {
  const [email,setEmail]=useState('admin@thermosense.local'); const [password,setPassword]=useState(''); const [error,setError]=useState(''); const [busy,setBusy]=useState(false)
  const submit=async event=>{event.preventDefault();setError('');setBusy(true);try{const result=await requestLogin({email,password});localStorage.setItem('thermosense-token',result.access_token);onAuthenticated(result.user)}catch(e){setError(e.response?.data?.detail||'Unable to sign in. Check that the API is running and your credentials are correct.')}finally{setBusy(false)}}
  return <div className="auth-screen"><div className="auth-card"><div className="auth-brand"><div className="brand-mark"><Activity size={21}/></div><div><strong>Thermo<span>Sense</span></strong><small>FIELD MONITORING</small></div></div><div className="auth-heading"><div className="auth-icon"><KeyRound size={19}/></div><h1>Welcome back</h1><p>Sign in to access the monitoring workspace.</p></div>{error&&<div className="auth-error"><AlertTriangle size={15}/>{error}</div>}<form onSubmit={submit}><label>Email address<input type="email" autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><button className="button button-primary auth-submit" disabled={busy}>{busy?'Signing in…':'Sign in'}<ChevronRight size={16}/></button></form><div className="auth-demo"><ShieldCheck size={14}/><span>Demo admin account is configured with <code>ADMIN_EMAIL</code> and <code>ADMIN_PASSWORD</code> in the backend environment.</span></div><p className="auth-disclaimer">ThermoSense is an engineering research prototype. Predictions are not clinical diagnoses.</p></div></div>
}

function Overview({ overview, fog, simulation, alerts, onToggle, isAdmin }) {
  const [scenario, setScenario] = useState('normal'); const [users, setUsers] = useState(3); const [interval, setIntervalValue] = useState(2)
  const readings = overview?.latest_readings || []
  const distribution = ['LOW', 'MODERATE', 'HIGH'].map(risk => ({ name: riskName[risk], value: readings.filter(x => x.risk === risk).length, key: risk }))
  return <>
    <PageHeading eyebrow={new Date().toLocaleDateString(undefined, { weekday: 'long', month: 'long', day: 'numeric' }).toUpperCase()} title="Monitoring overview" subtitle="A real-time view of your monitored workforce and system health."
      action={<button className="button button-secondary" onClick={() => window.location.reload()}><Activity size={16}/> Refresh data</button>}/>
    <div className="stat-grid">
      <StatCard icon={Users} label="Monitored users" value={overview?.monitored_users} note="Current active profiles" tone="blue"/>
      <StatCard icon={Radio} label="Connected devices" value={overview?.active_devices} note="Simulated device nodes" tone="mint"/>
      <StatCard icon={Thermometer} label="High risk users" value={overview?.high_risk_users} note="Based on latest prediction" tone="rose"/>
      <StatCard icon={AlertTriangle} label="Active alerts" value={overview?.active_alerts} note="Warnings & emergencies" tone="amber"/>
    </div>
    <section className="panel simulator-panel"><div className="panel-head"><div><div className="panel-title-row"><div className="section-icon purple"><Radio size={17}/></div><h2>Simulation control</h2><span className={`status-tag ${simulation?.running ? 'running' : ''}`}><i/>{simulation?.running ? 'Running' : 'Stopped'}</span></div><p>Generate realistic sensor readings through the live processing pipeline.</p></div><div className="sim-mode"><span className="mode-indicator"/>{simulation?.running ? `${riskName[(simulation.scenario || 'normal').toUpperCase()] || 'Normal'} scenario` : 'Ready to simulate'}</div></div>
      {isAdmin?<div className="sim-controls"><label>Scenario<select value={scenario} onChange={e => setScenario(e.target.value)}><option value="normal">Normal</option><option value="moderate">Moderate risk</option><option value="high">High risk</option></select></label><label>Number of users<select value={users} onChange={e => setUsers(Number(e.target.value))}><option value="1">1 user</option><option value="3">3 users</option><option value="5">5 users</option><option value="10">10 users</option></select></label><label>Update interval<select value={interval} onChange={e => setIntervalValue(Number(e.target.value))}><option value="1">1 second</option><option value="2">2 seconds</option><option value="3">3 seconds</option><option value="5">5 seconds</option></select></label><div className="sim-buttons">{simulation?.running ? <button className="button button-stop" onClick={() => onToggle(null)}><span className="stop-square"/>Stop simulation</button> : <button className="button button-primary" onClick={() => onToggle({ scenario, users, interval_seconds: interval })}><Radio size={16}/>Start simulation</button>}</div></div>:<div className="sim-permission-note">Simulator controls are restricted to administrators.</div>}
    </section>
    <div className="content-grid overview-grid">
      <section className="panel chart-panel"><div className="panel-head compact"><div><h2>Latest sensor readings</h2><p>Most recent values from each monitored user</p></div><Link to="/live" className="text-link">View live monitoring <ChevronRight size={15}/></Link></div>
        {readings.length ? <div className="readings-table-wrap"><table><thead><tr><th>USER</th><th>BODY TEMP.</th><th>HEART RATE</th><th>AMBIENT</th><th>HUMIDITY</th><th>RISK LEVEL</th></tr></thead><tbody>{readings.slice(0,5).map(r => <tr key={r.user_id}><td><Link to={`/people/${r.user_id}`} className="user-cell"><span className="table-avatar">{String(r.user_id).padStart(2,'0')}</span><span>Worker {r.user_id}<small>Device SIM-{String(r.device_id).padStart(3,'0')}</small></span></Link></td><td><b>{r.body_temperature.toFixed(1)}°</b><small className="unit">C</small></td><td><b>{Math.round(r.heart_rate)}</b><small className="unit">bpm</small></td><td><b>{r.ambient_temperature.toFixed(1)}°</b><small className="unit">C</small></td><td><b>{Math.round(r.humidity)}%</b></td><td><RiskPill risk={r.risk}/></td></tr>)}</tbody></table></div> : <EmptyState title="No readings yet" text="Start the simulator to see live sensor values here."/>}
      </section>
      <section className="panel system-panel"><div className="panel-head compact"><div><h2>System status</h2><p>Service health at a glance</p></div><Settings2 size={17} className="muted"/></div><div className="system-list"><SystemStatus icon={Cpu} label="Fog processing node" detail={`${fog?.processed_readings ?? '—'} readings processed`} ok={Boolean(fog?.online)}/><SystemStatus icon={Activity} label="Random Forest model" detail={overview ? `${overview.model_metrics?.model_version ?? 'Model loaded'} · 3 risk classes` : 'Waiting for API connection'} ok={Boolean(overview)}/><SystemStatus icon={ShieldCheck} label="PostgreSQL database" detail={overview ? 'Connected to primary store' : 'Waiting for API connection'} ok={Boolean(overview)}/></div><div className="fog-latency"><span>Latest processing</span><strong>{formatTime(fog?.latest_processed_at)}</strong></div></section>
    </div>
    <section className="panel alerts-preview"><div className="panel-head compact"><div><h2>Recent active alerts</h2><p>Warnings and emergency events from the pipeline</p></div><Link to="/alerts" className="text-link">All alerts <ChevronRight size={15}/></Link></div>{alerts.length ? <div className="alert-list">{alerts.slice(0,4).map(a => <AlertRow key={a.id} alert={a}/>)}</div> : <EmptyState title="All clear" text="No active warning or emergency alerts."/>}</section>
    <div className="risk-footnote">Risk prediction is an engineering signal for demonstration. Follow your organization’s established safety procedures.</div>
  </>
}
function SystemStatus({ icon: Icon, label, detail, ok }) { return <div className="system-status"><div className="system-icon"><Icon size={17}/></div><div className="system-copy"><strong>{label}</strong><span>{detail}</span></div><span className={`service-state ${ok?'':'service-down'}`}><i/>{ok?'Operational':'Unavailable'}</span></div> }
function EmptyState({ title, text }) { return <div className="empty-state"><div className="empty-icon"><Activity size={19}/></div><strong>{title}</strong><span>{text}</span></div> }
function AlertRow({ alert, onResolve }) { const role=useContext(RoleContext);const canResolve=role==='admin'||role==='emergency_team';return <div className={`alert-row ${alert.risk.toLowerCase()}`}><div className="alert-symbol"><AlertTriangle size={16}/></div><div className="alert-main"><div><strong>Worker {alert.user_id}</strong><RiskPill risk={alert.risk}/></div><span>{alert.message}</span></div><time>{formatDate(alert.timestamp)}</time>{canResolve&&onResolve&&alert.status==='ACTIVE'&&<button className="resolve-button" onClick={()=>onResolve(alert.id)}>Resolve</button>}</div> }

function LivePage() {
  const [readings, setReadings] = useState([]); const [query, setQuery] = useState(''); const [updated, setUpdated] = useState(null)
  useEffect(() => { let on = true; const load = () => getLatest().then(data => { if (on) { setReadings(data); setUpdated(new Date()) } }).catch(() => {}); load(); const timer = setInterval(load, 2500); return () => { on = false; clearInterval(timer) } }, [])
  const visible = readings.filter(r => `worker ${r.user_id} sim-${r.device_id}`.includes(query.toLowerCase()))
  return <><PageHeading eyebrow="LIVE MONITORING" title="Live monitoring" subtitle="Current physiological and environmental signals for each monitored user." action={<span className="live-indicator page-live"><span className="pulse-dot"/> Auto-refresh · {formatTime(updated)}</span>}/><div className="live-banner"><div className="live-banner-icon"><Radio size={19}/></div><div><strong>Live feed connected</strong><span>Sensor readings pass through fog processing and the Random Forest risk model.</span></div><span className="live-banner-state"><i/>Receiving</span></div><div className="toolbar"><div className="search-box"><Search size={16}/><input placeholder="Search workers or devices" value={query} onChange={e=>setQuery(e.target.value)}/></div><span className="result-count">{visible.length} monitored {visible.length === 1 ? 'user' : 'users'}</span></div><div className="user-card-grid">{visible.map(r => <UserCard key={r.user_id} reading={r}/>)}{!visible.length && <EmptyState title="No monitored users" text="Start the simulator to populate this view."/>}</div></>
}
function UserCard({ reading: r }) { return <Link to={`/people/${r.user_id}`} className={`user-card ${r.risk.toLowerCase()}`}><div className="user-card-head"><div className="user-card-id"><div className="table-avatar large">{String(r.user_id).padStart(2,'0')}</div><div><strong>Worker {r.user_id}</strong><span>SIM-{String(r.device_id).padStart(3,'0')} <i/> Active</span></div></div><RiskPill risk={r.risk}/></div><div className="vitals-grid"><Vital icon={Thermometer} label="Body temp" value={`${r.body_temperature.toFixed(1)}°C`}/><Vital icon={Activity} label="Heart rate" value={`${Math.round(r.heart_rate)} bpm`}/><Vital icon={Wind} label="Ambient" value={`${r.ambient_temperature.toFixed(1)}°C`}/><Vital icon={SlidersHorizontal} label="Humidity" value={`${Math.round(r.humidity)}%`}/></div><div className="user-card-foot"><span>Updated {formatTime(r.timestamp)}</span><span className="text-link">View details <ChevronRight size={14}/></span></div></Link> }
function Vital({ icon: Icon, label, value }) { return <div className="vital"><span><Icon size={14}/>{label}</span><strong>{value}</strong></div> }

function AccountManager() {
  const role=useContext(RoleContext);const [accounts,setAccounts]=useState([]);const [name,setName]=useState('');const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [accountRole,setAccountRole]=useState('user');const [error,setError]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false)
  const load=useCallback(()=>getManagedUsers().then(setAccounts).catch(e=>setError(e.response?.data?.detail||'Unable to load accounts.')),[])
  useEffect(()=>{if(role==='admin')load()},[role,load])
  if(role!=='admin')return null
  const submit=async event=>{event.preventDefault();setBusy(true);setError('');setNotice('');try{const created=await createManagedUser({name,email,password,role:accountRole});setAccounts(old=>[...old,created]);setName('');setEmail('');setPassword('');setNotice(`${created.name} account created.`)}catch(e){setError(e.response?.data?.detail||'Account creation failed.')}finally{setBusy(false)}}
  return <section className="panel account-manager"><div className="panel-head compact"><div><h2>Account management</h2><p>Admin-only · create User and Emergency Team logins</p></div><ShieldCheck size={18} className="muted"/></div><form className="account-form" onSubmit={submit}><label>Name<input required minLength="2" maxLength="100" value={name} onChange={e=>setName(e.target.value)} placeholder="Full name"/></label><label>Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="name@example.com"/></label><label>Temporary password<input required type="password" minLength="8" value={password} onChange={e=>setPassword(e.target.value)} placeholder="At least 8 characters"/></label><label>Role<select value={accountRole} onChange={e=>setAccountRole(e.target.value)}><option value="user">User</option><option value="emergency_team">Emergency Team</option></select></label><button className="button button-primary" disabled={busy}>{busy?'Creating…':'Create account'}</button></form>{error&&<div className="account-feedback error-text">{error}</div>}{notice&&<div className="account-feedback success-text">{notice}</div>}{accounts.length>0&&<div className="account-list"><div className="account-list-head"><strong>Application accounts</strong><span>{accounts.length} accounts</span></div><div className="account-chip-list">{accounts.map(account=><div className="account-chip" key={account.id}><span className="table-avatar">{account.name.slice(0,2).toUpperCase()}</span><span><strong>{account.name}</strong><small>{account.email}</small></span><em>{account.role.replace('_',' ')}</em></div>)}</div></div>}</section>
}

function PeoplePage() { const [users,setUsers] = useState([]); useEffect(()=>{ let on=true; const load=()=>getLatest().then(x=>on&&setUsers(x)).catch(()=>{}); load(); const t=setInterval(load,3000); return()=>{on=false;clearInterval(t)} },[]); return <><PageHeading eyebrow="DIRECTORY" title="Users & devices" subtitle="Monitored profiles and their simulated sensor assignments."/><div className="panel directory-panel"><div className="panel-head compact"><div><h2>Monitored users</h2><p>{users.length} user profiles discovered from incoming readings</p></div><Users size={19} className="muted"/></div>{users.length?<div className="readings-table-wrap"><table><thead><tr><th>USER PROFILE</th><th>DEVICE</th><th>BODY TEMP.</th><th>HEART RATE</th><th>LAST READING</th><th>RISK</th><th/></tr></thead><tbody>{users.map(r=><tr key={r.user_id}><td><Link to={`/people/${r.user_id}`} className="user-cell"><span className="table-avatar">{String(r.user_id).padStart(2,'0')}</span><span>Worker {r.user_id}<small>Monitoring profile</small></span></Link></td><td><span className="device-id"><Radio size={14}/> SIM-{String(r.device_id).padStart(3,'0')}</span></td><td>{r.body_temperature.toFixed(1)}°C</td><td>{Math.round(r.heart_rate)} bpm</td><td>{formatDate(r.timestamp)}</td><td><RiskPill risk={r.risk}/></td><td><Link className="row-link" to={`/people/${r.user_id}`}><ChevronRight size={17}/></Link></td></tr>)}</tbody></table></div>:<EmptyState title="No user profiles yet" text="Run the simulator to create monitored profiles."/>}</div></> }

function UserPage() { const {userId}=useParams(); const [data,setData]=useState(null); useEffect(()=>{let on=true;const load=()=>getUser(userId).then(x=>on&&setData(x)).catch(()=>{});load();const t=setInterval(load,3000);return()=>{on=false;clearInterval(t)}},[userId]);const history=[...(data?.readings||[])].reverse().map((r,i)=>({...r,time:formatTime(r.timestamp),point:i+1}));const last=data?.readings?.[0];return <><PageHeading eyebrow="MONITORED PROFILE" title={data?.name||`Worker ${userId}`} subtitle={`User ID ${userId} · Device ${data?.device_ids?.map(id=>`SIM-${String(id).padStart(3,'0')}`).join(', ')||'—'}`} action={last&&<RiskPill risk={last.risk}/>}/><div className="user-detail-stats">{last&&<><StatCard icon={Thermometer} label="Body temperature" value={`${last.body_temperature.toFixed(1)}°C`} note="Latest sensor value" tone="rose"/><StatCard icon={Activity} label="Heart rate" value={`${Math.round(last.heart_rate)} bpm`} note="Latest sensor value" tone="blue"/><StatCard icon={Wind} label="Ambient temperature" value={`${last.ambient_temperature.toFixed(1)}°C`} note="Latest sensor value" tone="amber"/><StatCard icon={SlidersHorizontal} label="Humidity" value={`${Math.round(last.humidity)}%`} note="Latest sensor value" tone="mint"/></>}</div><div className="panel chart-panel"><div className="panel-head compact"><div><h2>Sensor trend</h2><p>Recent body temperature readings · polled from the API</p></div></div>{history.length>1?<SensorChart data={history} dataKey="body_temperature" color="#e57f55" unit="°C"/>:<EmptyState title="Waiting for sensor history" text="More than one reading is needed to draw a trend."/>}</div><div className="panel alerts-preview"><div className="panel-head compact"><div><h2>Recent alerts</h2><p>Events linked to this profile</p></div></div>{data?.alerts?.length?<div className="alert-list">{data.alerts.slice(0,8).map(a=><AlertRow key={a.id} alert={a}/>)}</div>:<EmptyState title="No alerts for this user" text="Moderate and high predictions will appear here."/>}</div></> }

function AlertsPage() { const [items,setItems]=useState([]);const [risk,setRisk]=useState('all');const [status,setStatus]=useState('ACTIVE');const [message,setMessage]=useState('');const load=useCallback(()=>getAlerts({risk,status,limit:300}).then(setItems).catch(()=>{}),[risk,status]);useEffect(()=>{load();const t=setInterval(load,3000);return()=>clearInterval(t)},[load]);const resolve=async id=>{try{await resolveAlert(id);setMessage('Alert marked as resolved.');load()}catch{setMessage('Could not update this alert.')}};return <><PageHeading eyebrow="ALERT CENTER" title="Alerts" subtitle="In-app warnings and emergency events generated from model predictions." action={<div className="alert-total"><AlertTriangle size={16}/>{items.filter(a=>a.status==='ACTIVE').length} active</div>}/>{message&&<div className="success-banner">{message}<button onClick={()=>setMessage('')}><X size={15}/></button></div>}<div className="filter-row"><div className="segmented">{[['ACTIVE','Active'],['RESOLVED','Resolved'],['all','All']].map(([v,l])=><button className={status===v?'selected':''} key={v} onClick={()=>setStatus(v)}>{l}</button>)}</div><label className="select-filter"><SlidersHorizontal size={15}/><select value={risk} onChange={e=>setRisk(e.target.value)}><option value="all">All risk levels</option><option value="MODERATE">Moderate</option><option value="HIGH">High</option></select></label></div><div className="panel alert-page-panel"><div className="panel-head compact"><div><h2>Alert history</h2><p>{items.length} matching events · generated automatically from predictions</p></div></div>{items.length?<div className="alert-list">{items.map(a=><AlertRow key={a.id} alert={a} onResolve={resolve}/>)}</div>:<EmptyState title="No matching alerts" text={status==='ACTIVE'?'No active alerts right now. The system is monitoring readings.':'No alerts match those filters.'}/>}</div></> }

function HistoryPage() { const [items,setItems]=useState([]);const [risk,setRisk]=useState('');const [user,setUser]=useState('');const [query,setQuery]=useState('');const [loading,setLoading]=useState(true);const fetch=useCallback(()=>{setLoading(true);getReadings({limit:300,...(risk?{risk}:{}),...(user?{user_id:user}:{})}).then(setItems).catch(()=>setItems([])).finally(()=>setLoading(false))},[risk,user]);useEffect(()=>{fetch();const t=setInterval(fetch,5000);return()=>clearInterval(t)},[fetch]);const exportCsv=()=>{const header=['timestamp','user_id','device_id','body_temperature','heart_rate','ambient_temperature','humidity','risk','confidence'];const rows=items.map(r=>header.map(k=>r[k]).join(','));const blob=new Blob([[header.join(','),...rows].join('\n')],{type:'text/csv'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='thermosense-readings.csv';a.click();URL.revokeObjectURL(a.href)};const visible=items.filter(r=>!query||`worker ${r.user_id} sim-${r.device_id}`.includes(query.toLowerCase()));return <><PageHeading eyebrow="READING ARCHIVE" title="Historical data" subtitle="Search and filter stored readings and model predictions." action={<button className="button button-secondary" onClick={exportCsv} disabled={!items.length}><Download size={16}/>Export CSV</button>}/><div className="filter-row history-filters"><div className="search-box"><Search size={16}/><input placeholder="Search user or device" value={query} onChange={e=>setQuery(e.target.value)}/></div><label className="select-filter"><Users size={15}/><input value={user} onChange={e=>setUser(e.target.value.replace(/\D/g,''))} placeholder="User ID"/></label><label className="select-filter"><SlidersHorizontal size={15}/><select value={risk} onChange={e=>setRisk(e.target.value)}><option value="">All risk levels</option><option value="LOW">Low</option><option value="MODERATE">Moderate</option><option value="HIGH">High</option></select></label></div><div className="panel history-panel"><div className="panel-head compact"><div><h2>Sensor readings</h2><p>{loading?'Loading…':`${visible.length} records shown`}</p></div></div>{visible.length?<div className="readings-table-wrap"><table><thead><tr><th>TIMESTAMP</th><th>USER / DEVICE</th><th>BODY TEMP.</th><th>HEART RATE</th><th>AMBIENT</th><th>HUMIDITY</th><th>RISK</th><th>CONFIDENCE</th></tr></thead><tbody>{visible.map(r=><tr key={r.id}><td>{formatDate(r.timestamp)}</td><td><Link to={`/people/${r.user_id}`} className="history-user">Worker {r.user_id}<small>SIM-{String(r.device_id).padStart(3,'0')}</small></Link></td><td>{r.body_temperature.toFixed(1)}°C</td><td>{Math.round(r.heart_rate)} bpm</td><td>{r.ambient_temperature.toFixed(1)}°C</td><td>{Math.round(r.humidity)}%</td><td><RiskPill risk={r.risk}/></td><td>{(r.confidence*100).toFixed(0)}%</td></tr>)}</tbody></table></div>:<EmptyState title="No historical readings" text="Readings will appear after the simulator starts."/>}</div></> }

const riskColors = { LOW: '#43a778', MODERATE: '#dda83e', HIGH: '#d76f5b' }
function HistoryPageEnhancedLegacy() {
  const [items,setItems]=useState([]);const [risk,setRisk]=useState('');const [user,setUser]=useState('');const [query,setQuery]=useState('');const [start,setStart]=useState('');const [end,setEnd]=useState('');const [error,setError]=useState('');const [loading,setLoading]=useState(true)
  const load=useCallback(()=>{if(start&&end&&new Date(start)>new Date(end)){setError('Start date must be earlier than the end date.');setLoading(false);return}setLoading(true);setError('');getReadings({limit:300,...(risk?{risk}:{}),...(user?{user_id:user}:{}),...(start?{start:new Date(start).toISOString()}:{}),...(end?{end:new Date(end).toISOString()}:{})}).then(setItems).catch(e=>setError(e.response?.data?.detail||'Could not load historical readings.')).finally(()=>setLoading(false))},[risk,user,start,end])
  useEffect(()=>{load();const timer=setInterval(load,10000);return()=>clearInterval(timer)},[load])
  const visible=items.filter(r=>!query||`worker ${r.user_id} sim-${r.device_id}`.includes(query.toLowerCase()))
  const exportCsv=()=>{const cols=['timestamp','user_id','device_id','body_temperature','heart_rate','ambient_temperature','humidity','risk','confidence'];const csv=[cols.join(','),...visible.map(row=>cols.map(key=>row[key]).join(','))].join('\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));const anchor=document.createElement('a');anchor.href=url;anchor.download='thermosense-readings.csv';anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
  return <><PageHeading eyebrow="READING ARCHIVE" title="Historical data" subtitle="Filter stored readings by user, risk, and time range." action={<button className="button button-secondary" onClick={exportCsv} disabled={!visible.length}><Download size={16}/>Export CSV</button>}/><div className="filter-row history-filters"><div className="search-box"><Search size={16}/><input aria-label="Search user or device" placeholder="Search user or device" value={query} onChange={e=>setQuery(e.target.value)}/></div><label className="select-filter"><Users size={15}/><input aria-label="Filter by user ID" value={user} onChange={e=>setUser(e.target.value.replace(/\D/g,''))} placeholder="User ID"/></label><label className="select-filter"><SlidersHorizontal size={15}/><select aria-label="Filter by risk" value={risk} onChange={e=>setRisk(e.target.value)}><option value="">All risk levels</option><option value="LOW">Low</option><option value="MODERATE">Moderate</option><option value="HIGH">High</option></select></label><label className="date-filter"><span>From</span><input aria-label="Start date" type="datetime-local" value={start} onChange={e=>setStart(e.target.value)}/></label><label className="date-filter"><span>To</span><input aria-label="End date" type="datetime-local" value={end} onChange={e=>setEnd(e.target.value)}/></label><button className="button button-secondary" onClick={()=>{setStart('');setEnd('');setRisk('');setUser('');setQuery('')}}>Clear filters</button></div>{error&&<div className="error-banner"><AlertTriangle size={16}/><span>{error}</span><button onClick={load}>Retry</button></div>}<div className="panel history-panel"><div className="panel-head compact"><div><h2>Sensor readings</h2><p>{loading?'Loading records…':`${visible.length} records shown`}</p></div></div>{visible.length?<div className="readings-table-wrap"><table><thead><tr><th>TIMESTAMP</th><th>USER / DEVICE</th><th>BODY TEMP.</th><th>HEART RATE</th><th>AMBIENT</th><th>HUMIDITY</th><th>RISK</th><th>CONFIDENCE</th></tr></thead><tbody>{visible.map(r=><tr key={r.id}><td>{formatDate(r.timestamp)}</td><td><Link to={`/people/${r.user_id}`} className="history-user">Worker {r.user_id}<small>SIM-{String(r.device_id).padStart(3,'0')}</small></Link></td><td>{r.body_temperature.toFixed(1)}°C</td><td>{Math.round(r.heart_rate)} bpm</td><td>{r.ambient_temperature.toFixed(1)}°C</td><td>{Math.round(r.humidity)}%</td><td><RiskPill risk={r.risk}/></td><td>{(r.confidence*100).toFixed(0)}%</td></tr>)}</tbody></table></div>:<EmptyState title={loading?'Loading historical data':'No readings match these filters'} text={loading?'Querying the monitoring database…':'Adjust or clear the filters, or start the simulator to create readings.'}/>}</div></>
}

function HistoryPageEnhanced() {
  const [items,setItems]=useState([]);const [risk,setRisk]=useState('');const [user,setUser]=useState('');const [query,setQuery]=useState('');const [start,setStart]=useState('');const [end,setEnd]=useState('');const [error,setError]=useState('');const [loading,setLoading]=useState(true)
  const load=useCallback(()=>{if(start&&end&&new Date(start)>new Date(end)){setError('Start date must be earlier than the end date.');setLoading(false);return}setLoading(true);setError('');getReadings({limit:300,...(risk?{risk}:{}),...(user?{user_id:user}:{}),...(start?{start:new Date(start).toISOString()}:{}),...(end?{end:new Date(end).toISOString()}:{})}).then(setItems).catch(e=>setError(e.response?.data?.detail||'Could not load historical readings.')).finally(()=>setLoading(false))},[risk,user,start,end])
  useEffect(()=>{load();const timer=setInterval(load,10000);return()=>clearInterval(timer)},[load])
  const visible=items.filter(r=>!query||`worker ${r.user_id} sim-${r.device_id}`.includes(query.toLowerCase()))
  const exportCsv=()=>{const cols=['timestamp','user_id','device_id','body_temperature','heart_rate','ambient_temperature','humidity','risk','confidence'];const csv=[cols.join(','),...visible.map(row=>cols.map(key=>row[key]).join(','))].join('\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));const anchor=document.createElement('a');anchor.href=url;anchor.download='thermosense-readings.csv';anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
  return <><PageHeading eyebrow="READING ARCHIVE" title="Historical data" subtitle="Filter stored readings by user, risk, and time range." action={<button className="button button-secondary" onClick={exportCsv} disabled={!visible.length}><Download size={16}/>Export CSV</button>}/><div className="filter-row history-filters"><div className="search-box"><Search size={16}/><input aria-label="Search user or device" placeholder="Search user or device" value={query} onChange={e=>setQuery(e.target.value)}/></div><label className="select-filter"><Users size={15}/><input aria-label="Filter by user ID" value={user} onChange={e=>setUser(e.target.value.replace(/\D/g,''))} placeholder="User ID"/></label><label className="select-filter"><SlidersHorizontal size={15}/><select aria-label="Filter by risk" value={risk} onChange={e=>setRisk(e.target.value)}><option value="">All risk levels</option><option value="LOW">Low</option><option value="MODERATE">Moderate</option><option value="HIGH">High</option></select></label><label className="date-filter"><span>From</span><input aria-label="Start date" type="datetime-local" value={start} onChange={e=>setStart(e.target.value)}/></label><label className="date-filter"><span>To</span><input aria-label="End date" type="datetime-local" value={end} onChange={e=>setEnd(e.target.value)}/></label><button className="button button-secondary" onClick={()=>{setStart('');setEnd('');setRisk('');setUser('');setQuery('')}}>Clear filters</button></div>{error&&<div className="error-banner"><AlertTriangle size={16}/><span>{error}</span><button onClick={load}>Retry</button></div>}<div className="panel history-panel"><div className="panel-head compact"><div><h2>Sensor readings</h2><p>{loading?'Loading records…':`${visible.length} records shown`}</p></div></div>{visible.length?<div className="readings-table-wrap"><table><thead><tr><th>TIMESTAMP</th><th>USER / DEVICE</th><th>BODY TEMP.</th><th>HEART RATE</th><th>AMBIENT</th><th>HUMIDITY</th><th>RISK</th><th>CONFIDENCE</th></tr></thead><tbody>{visible.map(r=><tr key={r.id}><td>{formatDate(r.timestamp)}</td><td><Link to={`/people/${r.user_id}`} className="history-user">Worker {r.user_id}<small>SIM-{String(r.device_id).padStart(3,'0')}</small></Link></td><td>{r.body_temperature.toFixed(1)}°C</td><td>{Math.round(r.heart_rate)} bpm</td><td>{r.ambient_temperature.toFixed(1)}°C</td><td>{Math.round(r.humidity)}%</td><td><RiskPill risk={r.risk}/></td><td>{(r.confidence*100).toFixed(0)}%</td></tr>)}</tbody></table></div>:<EmptyState title={loading?'Loading historical data':'No readings match these filters'} text={loading?'Querying the monitoring database…':'Adjust or clear the filters, or start the simulator to create readings.'}/>}</div></>
}

function RiskAnalysisPage() {
  const [data, setData] = useState(null)
  const load = useCallback(() => getAnalytics().then(setData).catch(() => {}), [])
  useEffect(() => { load(); const timer = setInterval(load, 5000); return () => clearInterval(timer) }, [load])
  const trend = (data?.trend || []).map(point => ({ ...point, time: formatTime(point.timestamp) }))
  const distribution = ['LOW', 'MODERATE', 'HIGH'].map(key => ({ key, name: riskName[key], value: data?.risk_distribution?.[key] || 0 })).filter(x => x.value > 0)
  const metrics = data?.model_metrics
  return <>
    <PageHeading eyebrow="HISTORICAL ANALYTICS" title="Risk analysis" subtitle="Live prediction distribution, sensor trends, and held-out model evaluation." action={<span className="live-indicator page-live"><span className="pulse-dot"/> API data · auto-refresh</span>}/>
    <div className="stat-grid analytics-stats"><StatCard icon={Activity} label="Total predictions" value={data?.total_predictions} note="Persisted model outputs" tone="blue"/><StatCard icon={Thermometer} label="Avg. body temperature" value={data ? `${data.averages.body_temperature.toFixed(1)}°C` : '—'} note="Across recorded readings" tone="rose"/><StatCard icon={Activity} label="Avg. heart rate" value={data ? `${Math.round(data.averages.heart_rate)} bpm` : '—'} note="Across recorded readings" tone="blue"/><StatCard icon={Wind} label="Avg. ambient temperature" value={data ? `${data.averages.ambient_temperature.toFixed(1)}°C` : '—'} note={`Humidity average ${data?.averages?.humidity ?? '—'}%`} tone="amber"/></div>
    <div className="content-grid analytics-grid"><section className="panel chart-panel"><div className="panel-head compact"><div><h2>Risk distribution</h2><p>Prediction counts stored in the database</p></div></div>{distribution.length?<div className="risk-chart-layout"><div className="risk-pie"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={distribution} dataKey="value" nameKey="name" innerRadius={58} outerRadius={84} paddingAngle={3} stroke="none">{distribution.map(item=><Cell key={item.key} fill={riskColors[item.key]}/>)}</Pie><Tooltip formatter={(v,n)=>[v,`${n} predictions`]}/><Legend verticalAlign="bottom" height={25} iconType="circle" wrapperStyle={{fontSize:10,color:'#78869a'}}/></PieChart></ResponsiveContainer></div><div className="risk-counts">{distribution.map(item=><div key={item.key}><span className={`risk-key ${item.key.toLowerCase()}`}/><span>{item.name} risk</span><strong>{item.value.toLocaleString()}</strong></div>)}</div></div>:<EmptyState title="No predictions yet" text="Risk distribution will appear after readings are processed."/>}</section>
      <section className="panel chart-panel"><div className="panel-head compact"><div><h2>Sensor trends</h2><p>Latest stored body temperature and heart rate readings</p></div></div>{trend.length>1?<div className="chart-wrap analytics-trend"><ResponsiveContainer width="100%" height="100%"><AreaChart data={trend} margin={{top:12,right:10,left:-15,bottom:0}}><defs><linearGradient id="tempFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#d97e5f" stopOpacity={.17}/><stop offset="100%" stopColor="#d97e5f" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#edf0f5" vertical={false}/><XAxis dataKey="time" tickLine={false} axisLine={false} tick={{fontSize:9,fill:'#8792a3'}} minTickGap={35}/><YAxis yAxisId="temp" tickLine={false} axisLine={false} tick={{fontSize:9,fill:'#8792a3'}} width={39}/><YAxis yAxisId="heart" orientation="right" tickLine={false} axisLine={false} tick={{fontSize:9,fill:'#8792a3'}} width={35}/><Tooltip labelFormatter={(_,payload)=>payload?.[0]?.payload?.timestamp?formatDate(payload[0].payload.timestamp):''}/><Legend wrapperStyle={{fontSize:9}}/><Area yAxisId="temp" type="monotone" dataKey="body_temperature" name="Body temp °C" stroke="#d97e5f" strokeWidth={2} fill="url(#tempFill)" dot={false}/><Area yAxisId="heart" type="monotone" dataKey="heart_rate" name="Heart rate bpm" stroke="#6684b7" strokeWidth={2} fill="none" dot={false}/></AreaChart></ResponsiveContainer></div>:<EmptyState title="Waiting for sensor history" text="The chart appears after more than one reading."/>}</section></div>
    <section className="panel chart-panel model-panel"><div className="panel-head compact"><div><h2>Random Forest evaluation</h2><p>Held-out synthetic test split · distinct from live prediction results</p></div><span className="model-tag"><BadgeCheck size={14}/> {metrics?.model_version ?? 'Random Forest'}</span></div>{metrics?<><div className="metric-score-grid">{[['Accuracy',metrics.accuracy],['Macro precision',metrics.precision_macro],['Macro recall',metrics.recall_macro],['Macro F1',metrics.f1_macro]].map(([label,value])=><div className="metric-score" key={label}><span>{label}</span><strong>{(value*100).toFixed(1)}<small>%</small></strong></div>)}</div><div className="confusion-wrap"><div><strong>Confusion matrix</strong><span>Rows: actual class · columns: predicted class</span></div><table className="confusion-table"><thead><tr><th>Actual \ Pred.</th>{metrics.labels.map(label=><th key={label}>{riskName[label]}</th>)}</tr></thead><tbody>{metrics.confusion_matrix.map((row,i)=><tr key={metrics.labels[i]}><th>{riskName[metrics.labels[i]]}</th>{row.map((v,j)=><td className={i===j?'matrix-diagonal':''} key={j}>{v}</td>)}</tr>)}</tbody></table></div><p className="model-note">{metrics.evaluation_source}. The model has not been clinically validated.</p></>:<EmptyState title="Model evaluation is unavailable" text="Start the API to load its saved evaluation metrics."/>}</section>
    <div className="risk-footnote">Charts and live records are project demonstration analytics. Risk classifications are not medical diagnoses.</div>
  </>
}

function BlockchainPage() {
  const [data,setData]=useState({items:[],total:0}); const [verification,setVerification]=useState(null); const [busy,setBusy]=useState(false); const [error,setError]=useState('')
  const refresh=useCallback(async()=>{try{const [blocks,check]=await Promise.all([getBlocks({limit:100}),verifyBlockchain()]);setData(blocks);setVerification(check);setError('')}catch(e){setError(e.response?.data?.detail||'Blockchain API is unavailable. Start the backend and database.')}},[])
  useEffect(()=>{refresh();const timer=setInterval(refresh,8000);return()=>clearInterval(timer)},[refresh])
  const verifyNow=async()=>{setBusy(true);try{setVerification(await verifyBlockchain());setError('')}catch(e){setError(e.response?.data?.detail||'Verification request failed.')}finally{setBusy(false)}}
  return <><PageHeading eyebrow="RECORD INTEGRITY" title="Blockchain verification" subtitle="A local SHA-256 chain links stored predictions and their source readings." action={<button className="button button-primary" onClick={verifyNow} disabled={busy}><ShieldCheck size={16}/>{busy?'Verifying…':'Verify chain'}</button>}/>{error&&<div className="error-banner"><AlertTriangle size={16}/><span>{error}</span></div>}
    <div className={`verification-banner ${verification?.valid?'verified':''}`}><div className="verification-mark"><ShieldCheck size={20}/></div><div><strong>{verification?verification.valid?'Chain integrity verified':'Integrity issue found':'Verification pending'}</strong><span>{verification?verification.valid?`${verification.blocks_verified.toLocaleString()} blocks checked · each record hash and previous-block link is valid.`:`${verification.reason||'Verification failed'}${verification.broken_at!=null?` at block ${verification.broken_at}`:''}`:'Run verification to check the persisted SHA-256 chain.'}</span></div><span className="verification-state">{verification?.valid?'INTEGRITY OK':verification?'CHECK REQUIRED':'READY'}</span></div>
    <div className="stat-grid blockchain-stats"><StatCard icon={Fingerprint} label="Blocks stored" value={data.total} note="Prediction records in chain" tone="purple"/><StatCard icon={ShieldCheck} label="Verified blocks" value={verification?.blocks_verified ?? '—'} note="Latest verification result" tone="mint"/><div className="panel chain-head-card"><span>Latest chain hash</span><code>{verification?.latest_hash||'No blocks recorded yet'}</code></div></div>
    <section className="panel history-panel block-panel"><div className="panel-head compact"><div><h2>Block explorer</h2><p>Latest {data.items.length} of {data.total} chained prediction records</p></div><span className="hash-algorithm">SHA-256</span></div>{data.items.length?<div className="readings-table-wrap"><table><thead><tr><th>INDEX</th><th>TIMESTAMP</th><th>RECORD</th><th>RISK</th><th>DATA HASH</th><th>PREVIOUS HASH</th><th>BLOCK HASH</th></tr></thead><tbody>{data.items.map(block=><tr key={block.id}><td><span className="block-index">#{block.block_index}</span></td><td>{formatDate(block.timestamp)}</td><td>Prediction {block.prediction_id}</td><td><RiskPill risk={block.risk}/></td><td><code title={block.data_hash}>{block.data_hash.slice(0,14)}…</code></td><td><code title={block.previous_hash}>{block.previous_hash=== '0'.repeat(64)?'GENESIS':`${block.previous_hash.slice(0,14)}…`}</code></td><td><code title={block.current_hash}>{block.current_hash.slice(0,14)}…</code></td></tr>)}</tbody></table></div>:<EmptyState title="No blockchain records yet" text="Processed predictions are automatically added to the local chain."/>}</section>
    <p className="risk-footnote">This local hash chain demonstrates tamper detection. It is not a distributed public blockchain or a substitute for production security controls.</p>
  </>
}

function SensorChart({data,dataKey,color,unit}) { return <div className="chart-wrap"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data} margin={{top:12,right:12,left:-16,bottom:0}}><defs><linearGradient id="chartFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={color} stopOpacity={.18}/><stop offset="95%" stopColor={color} stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#edf0f5" vertical={false}/><XAxis dataKey="time" tickLine={false} axisLine={false} tick={{fontSize:11,fill:'#8792a3'}} minTickGap={35}/><YAxis tickLine={false} axisLine={false} tick={{fontSize:11,fill:'#8792a3'}} width={48}/><Tooltip contentStyle={{border:'1px solid #e9edf3',borderRadius:10,boxShadow:'0 6px 20px #13274612'}} formatter={v=>[`${Number(v).toFixed(1)} ${unit}`, 'Body temperature']}/><Area type="monotone" dataKey={dataKey} stroke={color} strokeWidth={2.5} fill="url(#chartFill)" dot={false} activeDot={{r:4,strokeWidth:0}}/></AreaChart></ResponsiveContainer></div> }

export default App
